server:
  port: 8090
  #eureka客户端配置
eureka:
  client:
    service-url: #注册中心地址
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true #实例名称更加倾向于ip地址 默认如此
spring:
  application:
    name: lagou-service-autodeliver
